baseurl: "https://candlegraph.netlify.app/"
languageCode: en-US
title: Candlegraph
theme: hugo-lithium
pagination:
  pagerSize: 5
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
permalinks:
  post: /:year/:month/:day/:slug/
menu:
  main:
    - name: Start Here!
      url: /start-here/
      weight: 10
    - name: Reviews
      url: /tags/reviews/
      weight: 20
    - name: Methodology
      url: /methodology/
      weight: 30
params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 3.2.2
  dateFormat: "January 2, 2006"
  description: A website calculating the value proposition of scented candles.
  favicon: favicon.ico
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  logo:
    alt: Logo
    height: 50
    url: logo.png
    width: 50
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true
    extensions:
      passthrough:
        enable: true
        delimiters:
          block:
            - - "$$"
              - "$$"
            - - "\\["
              - "\\]"
          inline:
            - - "$"
              - "$"
            - - "\\("
              - "\\)"
  highlight:
    codeFences: false

outputs:
  home:
    - HTML
    - RSS
    - JSON
    - jsonfeed

outputFormats:
  jsonfeed:
    mediaType: "application/json"
    baseName: "feed"
    isPlainText: true
    